###########
# site.title

title:    'DUNGEON CRAWLER'
subtitle: 'CS 175: Project in AI'


#########################
# more settings

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

markdown: kramdown

exclude:
- README.md
- LICENSE.md
